# Generated by Django 4.2.4 on 2023-10-11 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0007_following'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
